In [2]:
## Multiple Linear Regression

#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#import dataset
ds=pd.read_csv('C:/Users/dz234/OneDrive/Desktop/Learning Process/Applied Data Science/MLR_numeric.csv')
x=ds.iloc[:,:-1].values
y=ds.iloc[:,3].values
ds.head()

S&P department (spend)  Admin department(spend)  \
0                  101184                    70674   
1                   70132                    52030   
2                  149539                    98535   
3                   75821                    53649   
4                   97730                    68667   

   Operation department(spend)  Profit  
0                        97009  259480  
1                        63587  137019  
2                       199994  495552  
3                        66500  165057  
4                        91754  247841

In [4]:
# calculate corr
corr = ds.corr()
corr

S&P department (spend)  Admin department(spend)  \
S&P department (spend)                     1.000000                 0.984560   
Admin department(spend)                    0.984560                 1.000000   
Operation department(spend)                0.976437                 0.980723   
Profit                                     0.982576                 0.993823   

                             Operation department(spend)    Profit  
S&P department (spend)                          0.976437  0.982576  
Admin department(spend)                         0.980723  0.993823  
Operation department(spend)                     1.000000  0.975566  
Profit                                          0.975566  1.000000

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, 
random_state = 0)
#Fitting simple linear regression to training set
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print('Coefficients,beta:', regressor.coef_)
print('Constant,alpha:', regressor.predict([[0,0,0]]))

Coefficients,beta: [ 0.74568222  6.6837466  -0.17261534]
Constant,alpha: [-245992.40257836]


In [16]:
#Predicting the results for test set
y_pred=regressor.predict(x_test)
print(y_pred)
print(y_test)

[474262.32345618 311167.2377158  182212.30728899 254661.21837792
 489577.11092428 388254.76244367 216897.80322374 227697.88060702
 456234.34442673 269997.80127102]
[466013 305250 188824 241206 495552 397289 222793 229567 438294 247841]


In [11]:
#calculate the correlation coefficient 
corr = np.corrcoef(y_pred, y_test)
print(corr)

[[1.         0.99521366]
 [0.99521366 1.        ]]


In [17]:
# calculate the MSE 
from sklearn.metrics import mean_squared_error

MSE=mean_squared_error(y_test, y_pred)
print(MSE)

129616592.25129478


In [23]:
#Simple Linear Regression – Step 4
#Visualizing Training set result
#plt.scatter(x_train,y_train,color='blue') # plot the points
#plt.plot(x_train, regressor.predict(x_train),color='red') # plot the line
#plt.title('Advert Cost vs Sales (Training set)')
#plt.xlabel('Adverising Cost')
#plt.ylabel('Sales')
#plt.show()


In [24]:
a=[[90020,55200,94230]]
y_predict=regressor.predict(a)
print(y_predict)


[173811.18025181]


# 2nd Exercise 

In [37]:
#import dataset
ds=pd.read_csv('C:/Users/dz234/OneDrive/Desktop/Learning Process/Applied Data Science/MLR_mix.csv')
x=ds.iloc[:,:-1].values
y=ds.iloc[:,4].values
ds.head()

S&P department (spend)  Admin department(spend)  \
0                  101184                    70674   
1                   70132                    52030   
2                  149539                    98535   
3                   75821                    53649   
4                   97730                    68667   

   Operation department(spend) state  Profit  
0                        97009     A  259480  
1                        63587     B  137019  
2                       199994     A  495552  
3                        66500     B  165057  
4                        91754     B  247841

In [38]:
# calculate corr
corr = ds.corr()
corr

S&P department (spend)  Admin department(spend)  \
S&P department (spend)                     1.000000                 0.984560   
Admin department(spend)                    0.984560                 1.000000   
Operation department(spend)                0.976437                 0.980723   
Profit                                     0.982576                 0.993823   

                             Operation department(spend)    Profit  
S&P department (spend)                          0.976437  0.982576  
Admin department(spend)                         0.980723  0.993823  
Operation department(spend)                     1.000000  0.975566  
Profit                                          0.975566  1.000000

In [39]:
#Multiple Linear Regression – Step 2:
#Handling or Encode categorical variables

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x = LabelEncoder()
x[:, 3] = labelencoder_x.fit_transform(x[:, 3])

ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)
print(x)

[[1.0 0.0 101184 70674 97009]
 [0.0 1.0 70132 52030 63587]
 [1.0 0.0 149539 98535 199994]
 [0.0 1.0 75821 53649 66500]
 [0.0 1.0 97730 68667 91754]
 [0.0 1.0 84544 60923 81618]
 [1.0 0.0 117490 85379 146277]
 [0.0 1.0 119913 86499 150579]
 [0.0 1.0 145244 95108 189066]
 [1.0 0.0 147217 95598 190309]
 [0.0 1.0 81746 56815 72351]
 [1.0 0.0 107967 74058 106215]
 [1.0 0.0 74692 52493 64267]
 [1.0 0.0 72228 52210 63719]
 [0.0 1.0 96292 68521 90007]
 [1.0 0.0 124506 86995 153382]
 [0.0 1.0 113543 82796 122345]
 [1.0 0.0 142585 94589 184603]
 [1.0 0.0 118057 86227 146948]
 [1.0 0.0 86260 63082 85320]
 [1.0 0.0 63601 51026 59932]
 [1.0 0.0 113200 76388 115984]
 [0.0 1.0 141331 93725 171453]
 [1.0 0.0 79667 54864 69102]
 [0.0 1.0 112208 75407 115316]
 [1.0 0.0 82622 59754 72987]
 [0.0 1.0 127721 88888 153477]
 [0.0 1.0 117901 85532 146822]
 [0.0 1.0 147364 96275 191812]
 [1.0 0.0 110661 75404 114864]
 [0.0 1.0 107360 73604 100773]
 [0.0 1.0 87194 63403 87468]
 [1.0 0.0 75381 52575 66116]
 [1.0 

In [40]:
# Multiple linear regression - Step 3
x = x[:,1:] #keep B
print(x)

[[0.0 101184 70674 97009]
 [1.0 70132 52030 63587]
 [0.0 149539 98535 199994]
 [1.0 75821 53649 66500]
 [1.0 97730 68667 91754]
 [1.0 84544 60923 81618]
 [0.0 117490 85379 146277]
 [1.0 119913 86499 150579]
 [1.0 145244 95108 189066]
 [0.0 147217 95598 190309]
 [1.0 81746 56815 72351]
 [0.0 107967 74058 106215]
 [0.0 74692 52493 64267]
 [0.0 72228 52210 63719]
 [1.0 96292 68521 90007]
 [0.0 124506 86995 153382]
 [1.0 113543 82796 122345]
 [0.0 142585 94589 184603]
 [0.0 118057 86227 146948]
 [0.0 86260 63082 85320]
 [0.0 63601 51026 59932]
 [0.0 113200 76388 115984]
 [1.0 141331 93725 171453]
 [0.0 79667 54864 69102]
 [1.0 112208 75407 115316]
 [0.0 82622 59754 72987]
 [1.0 127721 88888 153477]
 [1.0 117901 85532 146822]
 [1.0 147364 96275 191812]
 [0.0 110661 75404 114864]
 [1.0 107360 73604 100773]
 [1.0 87194 63403 87468]
 [0.0 75381 52575 66116]
 [0.0 113427 78653 119763]
 [1.0 103004 71720 100065]
 [1.0 109249 74209 109578]
 [1.0 134157 92647 167690]
 [0.0 116481 83866 141719]
 [1

In [42]:
# Split and call linear regression - Step 4
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, 
random_state = 0)
#Fitting simple linear regression to training set
regressor=LinearRegression()
regressor.fit(x_train,y_train)
#print('Coefficients,beta:', regressor.coef_)
#print('Constant,alpha:', regressor.predict([[0,0,0]]))

LinearRegression()

In [43]:
#Predicting the results for test set - Step 5 
y_pred=regressor.predict(x_test)
print(y_pred)
print(y_test)

[469131.79514153 314305.95098855 177031.76224272 251333.22466428
 492265.59457446 384791.47672058 212333.02403266 223303.09210661
 451563.42840049 265608.51763769]
[466013 305250 188824 241206 495552 397289 222793 229567 438294 247841]


In [44]:
#Prediction
x = [[1.0,90020.0,55200.0,94230.0]]#0 is A, 1 is B
y_predict=regressor.predict(x)
print(y_predict) 

[166756.20638859]
