In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#import dataset
ds=pd.read_csv('C:/Users/dz234/OneDrive/Desktop/Learning Process/Applied Data Science/LRT_car.csv')
ds

Montly Salary  age  Y/N
0             2386   18    0
1             2486   19    0
2             2586   20    0
3             2686   20    0
4             2756   20    0
..             ...  ...  ...
395          12557   60    1
396          14270   60    1
397          10262   60    1
398           7782   60    0
399          11186   60    1

[400 rows x 3 columns]

In [3]:
ds.shape

(400, 3)

In [4]:
# Assign attribute to x and y
x=ds.iloc[:,:-1].values
y=ds.iloc[:,2].values

In [5]:
# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 
0.25, random_state = 0)


In [6]:
# Naïve Bayes Classifier– Step 3
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [7]:
# set is to get unique data , then make it into list follow by sort
# after sortm data in squence 0,1,2

#i = 0
#for i in range(0,4):
   # d=list(set(ds.iloc[:,i].values))
   # d.sort()
   # print(i,d)
   # i=i+1

In [8]:
#Handling or Encode categorical variables
#from sklearn.preprocessing import LabelEncoder
#labelencoder_X = LabelEncoder()
#x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
#x[:, 1] = labelencoder_X.fit_transform(x[:, 1])
#x[:, 2] = labelencoder_X.fit_transform(x[:, 2])
#x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
#print(x)

In [9]:
#fitting Naïve Bayes Classifier to the dataset 
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier=classifier.fit(x_train,y_train)

#discrete data used bernoulli 
#continous/numeric data used gaussian

In [10]:
# Naïve Bayes Classifier– Step 5
#Predict the test set results
y_pred=classifier.predict(x_test)


In [11]:
# Naïve Bayes Classifier– Step 6
#Making Confusion Matrix – to check whether the test set gives the correct result
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[47,  2],
       [ 8, 43]], dtype=int64)

In [12]:
y_test,y_pred

(array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64))

In [13]:
y_pred_new=classifier.predict(sc_x.transform(np.array([[15000,21]])))
print(y_pred_new)

[1]
