In [15]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [16]:
#import dataset Step 1
ds=pd.read_csv('C:/Users/dz234/OneDrive/Desktop/Learning Process/Applied Data Science/buy_car.csv')
ds.head()

Montly Salary  age  Y/N
0           2386   18    0
1           2486   19    0
2           2586   20    0
3           2686   20    0
4           2756   20    0

In [17]:
x=ds.iloc[:,:-1].values
y=ds.iloc[:,2].values

In [18]:
#splitting the dataset into training and test sets , Step 2
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)


In [19]:
# Naïve Bayes Classifier– Step 3 (no need)
#Feature Scaling
#from sklearn.preprocessing import StandardScaler
#sc_x=StandardScaler()
#x_train=sc_x.fit_transform(x_train)
#x_test=sc_x.transform(x_test)

In [26]:
# Random Forest Classification – Step 4
#fitting Random Forest Classification classifier to the training set 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0) 
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [27]:
#Decision Tree – Step 5
#Predict the test set results
y_pred=classifier.predict(x_test)

In [28]:
y_pred,y_test

(array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int64))

In [29]:
#Logistic Regression – Step 6
#Making Confusion Matrix – to check whether the test set gives the correct result
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[47,  2],
       [ 8, 43]], dtype=int64)

In [30]:
# Check the accuracy - Step 7
from sklearn.metrics import accuracy_score 
AR = accuracy_score(y_test,y_pred)
AR

0.9

In [33]:
y_pred_new=classifier.predict([[15000,21]])
print(y_pred_new)

[0]
