In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#import dataset
ds=pd.read_csv('C:/Users/dz234/OneDrive/Desktop/Learning Process/Applied Data Science/play.csv')
x=ds.iloc[:,:-1].values
y=ds.iloc[:,4].values
ds.head()

outlook temperature humidity  windy Play(Y/N)
0   Sunny         Hot     High  False        No
1   Sunny         Hot     High   True        No
2   Rainy        Mild     High  False       Yes
3   Rainy        Cool   Normal  False       Yes
4   Rainy        Cool   Normal   True        No

In [3]:
# set is to get unique data , then make it into list follow by sort
# after sortm data in squence 0,1,2

i = 0
for i in range(0,4):
    d=list(set(ds.iloc[:,i].values))
    d.sort()
    print(i,d)
    i=i+1

0 ['Rainy', 'Sunny']
1 ['Cool', 'Hot', 'Mild']
2 ['High', 'Normal']
3 [False, True]


In [4]:
#Handling or Encode categorical variables
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])
x[:, 2] = labelencoder_X.fit_transform(x[:, 2])
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
print(x)

[[1 1 0 0]
 [1 1 0 1]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 0]
 [1 0 1 0]
 [0 2 1 0]
 [1 2 1 1]
 [0 2 0 1]]


In [5]:
#fitting Naïve Bayes Classifier to the dataset 
from sklearn.naive_bayes import BernoulliNB
classifier= BernoulliNB()
classifier=classifier.fit(x,y)

#discrete data used bernoulli 
#continous/numeric data used gaussian

In [6]:
#Predict using classifier
prediction=classifier.predict([[1., 0., 0., 0.]])#sunny day,cool temperature, humidity high, windy false 
print(prediction)

['No']
