In [1]:
# import numpy 
import numpy as np

In [4]:
X = np.array([1,2,3])
X

array([1, 2, 3])

In [3]:
# check dimension 
X.ndim

1

In [5]:
# check shape 
X.shape


(3,)

In [6]:
X.size

3

In [8]:
#check type
X.dtype

dtype('int32')

In [9]:
X[0,]

1

In [10]:
# read only first two elements 
X[:2]

array([1, 2])

In [12]:
np.save('X',X)

In [13]:
np.load("X.npy")

array([1, 2, 3])

In [16]:
Z = np.array([[1,2,3],[4,5,6]])

In [17]:
Z

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
Z.dtype

dtype('int32')

In [19]:
Z.shape

(2, 3)

In [20]:
Z.size

6

In [21]:
np.save('Z',Z)